### PR TITLE
Update Readme

### PR DESCRIPTION
**Pull request by mble**
This commit updates the README with more detailed explanation of the
commands, as well as removes references to commands that have been
merged into the core `heroku-pg` plugin.

* Update Readme with explanations of each command, and how it
  may be useful
* Remove commands that are no longer part of this plugin
* Remove emailing support in preference of raising an issue
  on the repository

### CODE REVIEW

**Comment by axelson** [comment]
Is there a reason that this cannot be merged?

**Comment by lyubo1** [comment]
@mble do you want to merge this when you get a chance?

**Comment by mble** [comment]
@lyubo1 Yeah, I'll merge it in tomorrow. I totally forgot I had this open.

**Comment by axelson** [comment]
Awesome, thanks!

**Pull request merged**
