### PR TITLE
proposed fix for adding schema output to fdw

### PR DESCRIPTION
**Pull request by jonmountjoy**
Proposed fix for https://github.com/heroku/heroku-pg-extras/issues/67

### CODE REVIEW

**Comment by prem-prakash** [comment]
it seems that it is still missing PORT

```sql
% heroku pg:fdwsql fun DATABASE_URL -a sushi
CREATE EXTENSION IF NOT EXISTS postgres_fdw;
DROP SERVER IF EXISTS fun_db;
CREATE SERVER fun_db
  FOREIGN DATA WRAPPER postgres_fdw
  OPTIONS (dbname 'yyyyyy', host 'xxxxx.compute-1.amazonaws.com');
CREATE USER MAPPING FOR CURRENT_USER
  SERVER penny_db
  OPTIONS (user 'eeeeeee', password 'adadasdasdadasdasdasd');
psql: invalid port number: "undefined"
```

**Comment by uhoh-itsmaciek** [comment]
@prem-prakash I don't follow how you're getting this error message: are you piping the output of `pg:fdwsql` directly into psql, and getting an error there? Or are you getting an error while attempting to generate the sql itself, without actually running it?

**Comment by prem-prakash** [comment]
@uhoh-itsmaciek I ran this line:

```bash
% heroku pg:fdwsql fun DATABASE_URL -a sushi
```

and got this:

```sql
CREATE EXTENSION IF NOT EXISTS postgres_fdw;
DROP SERVER IF EXISTS fun_db;
CREATE SERVER fun_db
  FOREIGN DATA WRAPPER postgres_fdw
  OPTIONS (dbname 'yyyyyy', host 'xxxxx.compute-1.amazonaws.com');
CREATE USER MAPPING FOR CURRENT_USER
  SERVER penny_db
  OPTIONS (user 'eeeeeee', password 'adadasdasdadasdasdasd');
psql: invalid port number: "undefined"
```


there is an error: `psql: invalid port number: "undefined"`

and as I can see on the code, it is not taking port into account:

https://github.com/heroku/heroku-pg-extras/blob/07cda801f3368676afd54b6fee8b2874f3487701/commands/fdwsql.js#L44

**Comment by uhoh-itsmaciek** [comment]
Ok, I think there's actually a different issue here. Can you try the branch in #140 (see the `plugins:link` command) and let me know if that fixes your problem?

**Comment by prem-prakash** [comment]
@uhoh-itsmaciek yes I can try, but how do you I do?

**Comment by prem-prakash** [comment]
Yes @uhoh-itsmaciek it worked!

**Comment by uhoh-itsmaciek** [comment]
@prem-prakash check out that branch locally and run `heroku plugins:link .` in that directory.

**Comment by uhoh-itsmaciek** [comment]
Ok, awesome! Thanks for confirming! We'll get this merged and officially released shortly. Please remember to run `plugins:uninstall heroku-pg-extras` to undo the `plugins:link` (you may need to reinstal afterward).

**Comment by prem-prakash** [comment]
BTW what is the diference between pg:fdwsql and pg:links ?

**Comment by uhoh-itsmaciek** [comment]
@prem-prakash `pg:fdwsql` predates `pg:links`, and is just a simple way to automatically generate the necessary DDL to establish a foreign data wrapper to another table. `pg:links` acts as more of a "first class" concept in Heroku Postgres and, e.g., will update the foreign server credentials in all linked databases if the "target" credentials change. You should definitely use `pg:links` instead of `pg:fdwsql` unless it doesn't meet your use case (in which case we'd love to hear more at postgres@heroku.com ).

**Pull request closed without merging**
